#!/bin/bash
#
#======================================================
#setenv SCRAM_ARCH slc5_amd64_gcc434
#cmsrel CMSSW_4_2_3_patch2
#cd CMSSW_4_2_3_patch2/src
#cmsenv
#--- Used tags: HLT, RECO
cvs co -r V01-14-05-06   EventFilter/EcalRawToDigi                        
cvs co -r V11-07-26      HLTrigger/Configuration                          
cvs co -r V00-08-06      HLTrigger/Egamma                                 
cvs co -r V01-22-02      HLTrigger/HLTfilters                             
cvs co -r V00-02-12      HLTrigger/JetMET                                 
cvs co -r V02-11-03      HLTrigger/Muon                                   
cvs co -r V03-02-00      HLTrigger/btau                                   
cvs co -r V01-21-02      HLTrigger/special                                
cvs co -r V01-04-06-04   RecoBTag/ImpactParameter                         
cvs co -r V00-13-10-00   RecoLocalCalo/EcalRecAlgos                       
cvs co -r V01-18-03-01   RecoMuon/MuonIdentification                      
cvs co -r V08-12-08-00   RecoTracker/MeasurementDet                       
#----> Don't forget (checkdeps)
#checkdeps -a
#scram b
#=======================================================
#--- Used tags: PAT
cvs co -r V06-04-12      DataFormats/PatCandidates
cvs co -r V08-06-27      PhysicsTools/PatAlgos
cvs co -r V03-09-18      PhysicsTools/PatUtils
cvs co -r V00-05-17      PhysicsTools/PatExamples
cvs co -r V07-02-09      PhysicsTools/Utilities



